version: '3.0'

services:
  docker:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6380:6379"
    restart: always