name: Java CI with Gradle

on:
  push:
    branches: [ "master" , "ci/*"]
  pull_request:
    branches: [ "master" , "ci/*"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      MYSQL_URL: ${{secrets.MYSQL_URL}}
      MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      SMS_API_KEY: ${{secrets.SMS_API_KEY}}
      SMS_SECRET_KEY: ${{secrets.SMS_SECRET_KEY}}
      FROM_PHONE_NUMBER: ${{secrets.FROM_PHONE_NUMBER}}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
